# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        rectangle_thumbnail_large:
            filters:
                thumbnail:
                    size: [550, 350]
                    mode: outbound
                    allow-upscale: true
                    
        rectangle_thumbnail_medium:
            filters:
                thumbnail:
                    size: [350, 150]
                    mode: outbound
                    allow-upscale: true

        rectangle_thumbnail_small:
            filters:
                thumbnail:
                    size: [300, 100]
                    mode: outbound
                    allow-upscale: true

        square_thumbnail_small:
            filters:
                thumbnail:
                    size: [90, 90]
                    mode: outbound
                    allow-upscale: true
        
        square_thumbnail_medium:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow-upscale: true

        square_thumbnail_large:
            filters:
                thumbnail:
                    size: [500, 500]
                    mode: outbound
                    allow-upscale: true